# Generated by Django 3.1.2 on 2021-09-11 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('created', 'created'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('packing', 'packing'), ('packed', 'packed'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('closed', 'closed'), ('cancelled', 'cancelled'), ('open_purchase_order', 'open_po'), ('close_purchase_order', 'closed_po')], default='created', max_length=32)),
                ('order_price_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_orders', to='farmer.farm')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_orders', to='farmer.farmer')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_feed_orders', to='custom_auth.address')),
            ],
            options={
                'ordering': ('-pk', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FeedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('feed_product_image', models.CharField(default='url', help_text='image s3 url', max_length=254)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('current_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(null=True)),
                ('charge_taxes', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('manage_products', 'Manage feed products.'),),
            },
        ),
        migrations.CreateModel(
            name='FeedProductDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('code', models.CharField(default='code', help_text='code', max_length=150, unique=True)),
                ('image', models.CharField(default='url', help_text='image s3 url', max_length=254)),
                ('is_visible', models.BooleanField(default=True)),
                ('hsn', models.CharField(default='0', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('city', models.CharField(default='City Name', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_auth.address')),
            ],
            options={
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='FeedProductSubDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('image', models.CharField(default='url', help_text='image s3 url', max_length=254)),
                ('is_visible', models.BooleanField(default=True)),
                ('code', models.CharField(default='code', help_text='code', max_length=150, unique=True)),
                ('feedProductDivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedwarehouse.feedproductdivision')),
            ],
        ),
        migrations.CreateModel(
            name='FeedProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(default='specification', max_length=200)),
                ('feedProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedSpecificationProduct', to='feedwarehouse.feedproduct')),
            ],
        ),
        migrations.AddField(
            model_name='feedproduct',
            name='feedProductDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_product_division', to='feedwarehouse.feedproductdivision'),
        ),
        migrations.AddField(
            model_name='feedproduct',
            name='feedProductSubDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_product_sub', to='feedwarehouse.feedproductsubdivision'),
        ),
        migrations.AddField(
            model_name='feedproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVendor', to='feedwarehouse.productvendor'),
        ),
        migrations.CreateModel(
            name='FeedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('feedProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedwarehouse.feedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FeedOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('feed_order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_order_lines', to='feedwarehouse.feedorder')),
                ('feed_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed_order_lines', to='feedwarehouse.feedproduct')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('feed_order', 'feed_product')},
            },
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inventory name', max_length=254)),
                ('desc', models.CharField(default='desc', max_length=256)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_status', models.CharField(choices=[('available', 'available'), ('in transit', 'in transit'), ('delivered', 'delivered')], default='available', max_length=200)),
                ('feedProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryFeedProducts', to='feedwarehouse.feedproduct')),
                ('feedWarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedwarehouse.feedwarehouse')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('feedWarehouse', 'name', 'feedProduct', 'inventory_status')},
            },
        ),
    ]
