# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributionchain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Normal', 'Normal')], default='Normal', max_length=200)),
                ('retailer_status', models.CharField(choices=[('Declined', 'Declined'), ('Shop Stock Available', 'Shop Stock Available'), ('Trip Stock Over', 'Trip Stock Over'), ('Trip Time Over', 'Trip Time Over'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Replaced', 'Replaced'), ('Sales Booked', 'Sales Booked'), ('No Action', 'No Action')], default='No Action', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RetailerDemandSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('product_supply_quantity', models.PositiveIntegerField(default=0)),
                ('product_out_quantity', models.PositiveIntegerField(default=0)),
                ('product_replacement_quantity', models.PositiveIntegerField(default=0)),
                ('product_return_quantity', models.PositiveIntegerField(default=0)),
                ('product_sold_quantity', models.PositiveIntegerField(default=0)),
                ('product_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_transfer_quantity', models.IntegerField(default=0)),
                ('product_fresh_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_return_repalce_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_fresh_stock_validated', models.CharField(default='Not Yet', max_length=100)),
                ('product_old_stock_validated', models.CharField(default='Not Yet', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDemandSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('product_supply_quantity', models.PositiveIntegerField(default=0)),
                ('product_out_quantity', models.PositiveIntegerField(default=0)),
                ('product_replacement_quantity', models.PositiveIntegerField(default=0)),
                ('product_return_quantity', models.PositiveIntegerField(default=0)),
                ('product_sold_quantity', models.PositiveIntegerField(default=0)),
                ('product_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_transfer_quantity', models.IntegerField(default=0)),
                ('product_fresh_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_return_repalce_in_quantity', models.PositiveIntegerField(default=0)),
                ('product_fresh_stock_validated', models.CharField(default='Not Yet', max_length=100)),
                ('product_old_stock_validated', models.CharField(default='Not Yet', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesEggsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brown', models.PositiveIntegerField(default=0)),
                ('white', models.PositiveIntegerField(default=0)),
                ('nutra', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesSupplySKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('beatWarehouseSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_supply_beat', to='distributionchain.beatwarehousesupply')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesSupplySKUProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSupplyPackedSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('beatWarehouseSupply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_packed_sku', to='distributionchain.beatwarehousesupply')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesPackedSKUProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSMApprovalSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('demand_classification', models.CharField(default='Gurgaon-GT', max_length=200)),
                ('beatSMApproval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_sm_approval_beat', to='distributionchain.beatsmapproval')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesSMApprovalSKUProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRHApprovalSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('beatRHApproval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_rh_approval_beat', to='distributionchain.beatrhapproval')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesRHApprovalSKUProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_status', models.CharField(choices=[('Manager', 'Manager'), ('Regional Manager', 'Regional Manager'), ('Worker', 'Worker')], default='Worker', max_length=100)),
                ('demand_classification', models.CharField(default='Gurgaon-GT', max_length=200)),
                ('working_status', models.CharField(choices=[('Resigned', 'Resigned'), ('Onboarded', 'Onboarded'), ('Cold', 'Cold')], default='Onboarded', max_length=100)),
                ('is_test_profile', models.BooleanField(default=False)),
                ('is_adhoc_profile', models.BooleanField(default=False)),
                ('is_mt_profile', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('distributionPersonProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributionchain.distributionpersonprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-management_status',),
            },
        ),
    ]
