# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributionchain', '__first__'),
        ('saleschain', '0001_initial'),
        ('product', '0001_initial'),
        ('retailer', '0002_auto_20210911_1424'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespersonprofile',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_sales', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='saleseggsdata',
            name='salesPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eggs_salesperson', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='salesdemandsku',
            name='beatAssignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_demand_beat', to='distributionchain.beatassignment'),
        ),
        migrations.AddField(
            model_name='salesdemandsku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesdemandSKUProduct', to='product.product'),
        ),
        migrations.AddField(
            model_name='salesdemandsku',
            name='salesRHApprovalSKU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_rh_approval_sku', to='saleschain.salesrhapprovalsku'),
        ),
        migrations.AddField(
            model_name='retailerdemandsku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandSKUProduct', to='product.product'),
        ),
        migrations.AddField(
            model_name='retailerdemandsku',
            name='retailerDemand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandSKU', to='saleschain.retailerdemand'),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='beatAssignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demand_beat_assignment', to='distributionchain.beatassignment'),
        ),
        migrations.AddField(
            model_name='retailerdemand',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demand_retailer', to='retailer.retailer'),
        ),
    ]
