# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('updated_at', models.DateTimeField(null=True)),
                ('paper_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('chatki_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('paper_price_updated_at', models.DateTimeField(null=True)),
                ('chatki_price_updated_at', models.DateTimeField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.city')),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('manage_products', 'Manage products.'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_available_online', models.BooleanField(default=True)),
                ('is_stock_available_online', models.BooleanField(default=False)),
                ('is_prime_online', models.BooleanField(default=True)),
                ('is_new_online', models.BooleanField(default=True)),
                ('rate_type', models.CharField(choices=[('margin', 'margin'), ('dealer', 'dealer')], default='margin', help_text='rate type', max_length=254)),
                ('brand_type', models.CharField(choices=[('branded', 'branded'), ('unbranded', 'unbranded')], default='branded', help_text='brand type', max_length=254)),
                ('product_image', models.CharField(default='url', help_text='image s3 url', max_length=254)),
                ('SKU_Count', models.IntegerField(default=30)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('oms_order', models.PositiveIntegerField(default=1)),
                ('ecomm_order', models.PositiveIntegerField(default=1)),
                ('current_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ecommerce_price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('shelf_life', models.CharField(default='21 days from the date of packaging', max_length=254)),
                ('sku_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_type', models.CharField(default='gms', help_text='gms', max_length=200)),
                ('updated_at', models.DateTimeField(null=True)),
                ('charge_taxes', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.city')),
            ],
            options={
                'ordering': ('oms_order',),
                'permissions': (('manage_products', 'Manage products.'),),
            },
        ),
        migrations.CreateModel(
            name='ProductDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('code', models.CharField(default='code', help_text='code', max_length=150, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('hsn', models.CharField(default='0407', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='informationProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=150)),
                ('description', models.CharField(help_text='description', max_length=254)),
                ('is_visible', models.BooleanField(default=True)),
                ('code', models.CharField(default='code', help_text='code', max_length=150, unique=True)),
                ('productDivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.productdivision')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='specificationProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLongDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='longDescriptionProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('quantity', models.IntegerField(default=0)),
                ('baseProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.baseproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inlineProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('info_value', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('type', models.CharField(default='gms', help_text='gms', max_length=200)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inlineInformationProduct', to='product.productinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptionProduct', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='benefitProduct', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_division', to='product.productdivision'),
        ),
        migrations.AddField(
            model_name='product',
            name='productSubDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_sub', to='product.productsubdivision'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='productDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_product_division', to='product.productdivision'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='productSubDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_product_sub', to='product.productsubdivision'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('SKU_Count', 'city', 'name', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='baseproduct',
            unique_together={('city', 'name')},
        ),
    ]
