# Generated by Django 3.1.2 on 2021-09-11 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_status', models.CharField(choices=[('Manager', 'Manager'), ('Regional Manager', 'Regional Manager'), ('Worker', 'Worker')], default='Worker', max_length=100)),
                ('working_status', models.CharField(choices=[('Resigned', 'Resigned'), ('Onboarded', 'Onboarded'), ('Cold', 'Cold')], default='Onboarded', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-management_status',),
            },
        ),
    ]
