# Generated by Django 3.1.2 on 2021-09-11 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_classification', models.CharField(default='Gurgaon-GT', max_length=200)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Normal', 'Normal')], default='Normal', max_length=200)),
                ('beat_material_status', models.CharField(choices=[('Demand', 'Demand'), ('Supply', 'Supply'), ('SMApproved', 'SMApproved'), ('RHApproved', 'RHApproved'), ('Approved', 'Approved'), ('Reported', 'Reported'), ('Loaded', 'Loaded'), ('Closed', 'Closed')], default='Demand', max_length=200)),
                ('beat_date', models.DateField(blank=True, null=True)),
                ('beat_expected_time', models.TimeField(blank=True, null=True)),
                ('beat_time', models.TimeField(blank=True, null=True)),
                ('beat_number', models.PositiveIntegerField(default=0)),
                ('beat_type', models.CharField(choices=[('Adhoc', 'Adhoc'), ('Regular', 'Regular')], default='Regular', max_length=200)),
                ('beat_type_number', models.PositiveIntegerField(default=0)),
                ('beat_name', models.CharField(default='name', max_length=200)),
                ('beat_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Assigned', 'Assigned'), ('Scheduled', 'Scheduled'), ('Planned', 'Planned')], default='Planned', max_length=200)),
                ('sc_in_time', models.TimeField(blank=True, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('ODO_in', models.IntegerField(default=0)),
                ('ODO_return', models.IntegerField(default=0)),
                ('distributor_trip_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=150)),
                ('warehouse_trip_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=150)),
                ('finance_trip_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=150)),
            ],
            options={
                'ordering': ('beat_date',),
            },
        ),
        migrations.CreateModel(
            name='BeatWarehouseSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_white_percentage', models.PositiveIntegerField(default=0)),
                ('supply_brown_percentage', models.PositiveIntegerField(default=0)),
                ('supply_nutra_percentage', models.PositiveIntegerField(default=0)),
                ('unpacked_white_eggs', models.PositiveIntegerField(default=0)),
                ('unpacked_brown_eggs', models.PositiveIntegerField(default=0)),
                ('unpacked_nutra_eggs', models.PositiveIntegerField(default=0)),
                ('beat_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionPersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_status', models.CharField(choices=[('Manager', 'Manager'), ('Regional Manager', 'Regional Manager'), ('Worker', 'Worker')], default='Worker', max_length=100)),
                ('working_status', models.CharField(choices=[('Resigned', 'Resigned'), ('Onboarded', 'Onboarded'), ('Cold', 'Cold')], default='Onboarded', max_length=100)),
                ('is_test_profile', models.BooleanField(default=False)),
                ('is_ecomm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-management_status',),
            },
        ),
        migrations.CreateModel(
            name='SMRelativeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_type', models.CharField(default='White', max_length=200)),
                ('relative_number', models.PositiveIntegerField(default=100)),
                ('demand_classification', models.CharField(default='Gurgaon-GT', max_length=200)),
                ('name', models.CharField(default='GGT-W', max_length=200)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TripSKUTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('warehouse', 'warehouse'), ('beat', 'beat'), ('satellite', 'satellite'), ('w-beat', 'w-beat')], default='beat', max_length=200)),
                ('transfer_status', models.CharField(default='Pending', max_length=200)),
                ('beat_date', models.DateField(null=True)),
                ('transferred_at', models.TimeField(default=django.utils.timezone.now)),
                ('from_beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferByBeat', to='distributionchain.beatassignment')),
                ('from_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferByDistributor', to='distributionchain.distributionpersonprofile')),
                ('to_beat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferToBeat', to='distributionchain.beatassignment')),
                ('to_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferToDistributor', to='distributionchain.distributionpersonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TransferSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('tripSKUTransfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tripTransferSKU', to='distributionchain.tripskutransfer')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionEggsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brown', models.PositiveIntegerField(default=0)),
                ('white', models.PositiveIntegerField(default=0)),
                ('nutra', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('distributionPerson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eggs_distributionperson', to='distributionchain.distributionpersonprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BeatSMApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_white_relative', models.PositiveIntegerField(default=0)),
                ('supply_brown_relative', models.PositiveIntegerField(default=0)),
                ('supply_nutra_relative', models.PositiveIntegerField(default=0)),
                ('beat_date', models.DateField(blank=True, null=True)),
                ('demand_classification', models.CharField(default='Gurgaon-GT', max_length=200)),
                ('beat_warehouse_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sm_warehouse_supply', to='distributionchain.beatwarehousesupply')),
            ],
        ),
        migrations.CreateModel(
            name='BeatRHApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_white_percentage', models.PositiveIntegerField(default=0)),
                ('supply_brown_percentage', models.PositiveIntegerField(default=0)),
                ('supply_nutra_percentage', models.PositiveIntegerField(default=0)),
                ('beat_date', models.DateField(blank=True, null=True)),
                ('beatSMApproval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_sm_approval', to='distributionchain.beatsmapproval')),
            ],
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignee', to='distributionchain.distributionpersonprofile'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='beatRHApproval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_rh_approval', to='distributionchain.beatrhapproval'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatDistributor', to='distributionchain.distributionpersonprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='beatassignment',
            unique_together={('beat_date', 'beat_number', 'beat_type', 'beat_type_number')},
        ),
    ]
