# Generated by Django 3.1.2 on 2021-09-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
        ('product', '0001_initial'),
        ('saleschain', '0002_auto_20210911_1424'),
        ('distributionchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatassignment',
            name='adhoc_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_vehicle_assignment', to='warehouse.adhocvehicle'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='beat_demand_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatDemandPerson', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='beat_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_person_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='beat_supply_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatDemandApprover', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='beat_supply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatSupplyPerson', to='warehouse.warehousepersonprofile'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_driver_assignment', to='warehouse.driver'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beat_vehicle_assignment', to='warehouse.vehicle'),
        ),
        migrations.AddField(
            model_name='beatassignment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatWarehouse', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='beatrhapproval',
            name='beat_supply_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatSupplyRHApprover', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='beatsmapproval',
            name='beat_supply_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatSupplySMApprover', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='beatwarehousesupply',
            name='beat_supply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatWarehouseSupplyPerson', to='warehouse.warehousepersonprofile'),
        ),
        migrations.AddField(
            model_name='distributionpersonprofile',
            name='warehouse',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_distribution', to='warehouse.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfersku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferSKUProduct', to='product.product'),
        ),
        migrations.AddField(
            model_name='tripskutransfer',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferFromWarehouse', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='tripskutransfer',
            name='from_warehouse_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferSentBy', to='warehouse.warehousepersonprofile'),
        ),
        migrations.AddField(
            model_name='tripskutransfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferToWarehouse', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='tripskutransfer',
            name='to_warehouse_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferAcceptedBy', to='warehouse.warehousepersonprofile'),
        ),
    ]
