# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saleschain', '0001_initial'),
        ('order', '0001_initial'),
        ('payment', '0002_salestransaction_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='salesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='saleschain.salespersonprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoice', to='payment.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='salesTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentTransactions', to='payment.salestransaction'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_lines', to='payment.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sales_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.salestransaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='order.order'),
        ),
    ]
