# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0002_auto_20210911_1424'),
        ('base', '0001_initial'),
        ('distributionchain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A B C', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=3, default=0, help_text='25', max_digits=12)),
                ('number_value', models.CharField(default='257', help_text='257', max_length=200)),
                ('type', models.CharField(default='%', help_text='%', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('white_number', models.DecimalField(decimal_places=3, default=0, help_text='5', max_digits=12)),
                ('brown_number', models.DecimalField(decimal_places=3, default=0, help_text='5', max_digits=12)),
                ('nutra_number', models.DecimalField(decimal_places=3, default=0, help_text='5', max_digits=12)),
                ('type', models.CharField(default='%', help_text='%', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='<10 Lakhs', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarginRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_rate', models.DecimalField(decimal_places=3, default=0, help_text='56', max_digits=12)),
                ('margin_mrp', models.DecimalField(decimal_places=3, default=0, help_text='56', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shop', models.CharField(max_length=200)),
                ('shop_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('billing_name_of_shop', models.CharField(default='Exact Name Of Shop', max_length=200)),
                ('code_string', models.CharField(blank=True, max_length=200, null=True)),
                ('code_int', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('billing_shipping_address_same', models.BooleanField(default=False)),
                ('beat_number', models.PositiveIntegerField(default=0)),
                ('beat_order_number', models.PositiveIntegerField(default=0)),
                ('rate_type', models.CharField(choices=[('margin', 'margin'), ('dealer', 'dealer'), ('mt', 'mt'), ('unbranded', 'unbranded')], default='margin', help_text='rate type', max_length=254)),
                ('GSTIN', models.CharField(default='GSTIN', max_length=200)),
                ('gst_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('gstin_status', models.CharField(choices=[('not-verified', 'not-verified'), ('uploaded', 'uploaded'), ('verified', 'verified')], default='not-verified', max_length=20)),
                ('onboarding_status', models.CharField(choices=[('Onboarded', 'Onboarded'), ('Cold', 'Cold'), ('Pending Interested', 'Pending Interested'), ('Closed', 'Closed'), ('Duplicate', 'Duplicate')], default='Onboarded', max_length=200)),
                ('onboarding_date', models.DateTimeField(blank=True, help_text='Onboarding Date', null=True)),
                ('last_order_date', models.DateTimeField(blank=True, help_text='Last Order Date', null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('amount_due', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('calc_amount_due', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('net_amount_due', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('annual_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='annual_income', to='retailer.incomeslab')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_billing_address', to='custom_auth.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='retailer.customer_category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.city')),
                ('classification', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retailer.classification')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.cluster')),
                ('commission_slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commission_slab', to='retailer.commissionslab')),
                ('discount_slab', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discount_slab', to='retailer.discountslab')),
            ],
            options={
                'ordering': ['-last_order_date'],
            },
        ),
        migrations.CreateModel(
            name='RetailerPaymentCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(default='Days', max_length=200)),
                ('is_mt', models.BooleanField(default=False)),
                ('is_gt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RetailerShorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GT', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RetailOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('owner_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_status', models.CharField(choices=[('not-verified', 'not-verified'), ('uploaded', 'uploaded'), ('verified', 'verified')], default='not-verified', max_length=20)),
                ('pancard_photo_url', models.CharField(blank=True, max_length=254, null=True)),
                ('pancard_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pancard_status', models.CharField(choices=[('not-verified', 'not-verified'), ('uploaded', 'uploaded'), ('verified', 'verified')], default='not-verified', max_length=20)),
                ('retail_shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_owners', to='retailer.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerEggsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brown', models.PositiveIntegerField(default=0)),
                ('white', models.PositiveIntegerField(default=0)),
                ('nutra', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eggs_retailer', to='retailer.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_number', models.PositiveIntegerField(default=0)),
                ('beat_type', models.CharField(choices=[('Adhoc', 'Adhoc'), ('Regular', 'Regular')], default='Regular', max_length=200)),
                ('beat_area', models.CharField(default='beat area', max_length=200)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributionchain.distributionpersonprofile')),
            ],
        ),
    ]
