# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributionchain', '__first__'),
        ('custom_auth', '0002_auto_20210911_1424'),
        ('saleschain', '0001_initial'),
        ('supplychain', '0001_initial'),
        ('base', '0001_initial'),
        ('farmer', '0002_auto_20210911_1424'),
        ('finance', '__first__'),
        ('operationschain', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_desc', models.CharField(max_length=256, null=True)),
                ('vehicle_no', models.CharField(default='Vehicle No', max_length=254)),
                ('vehicle_identifier_type', models.CharField(default='Echo', max_length=254)),
                ('vendor', models.CharField(default='vendor name', max_length=254)),
                ('vendor_contact_no', phonenumber_field.modelfields.PhoneNumberField(default='+911234567890', max_length=128, region='IN')),
                ('vehicle_photo_url', models.CharField(max_length=254, null=True)),
                ('vendor_photo_url', models.CharField(max_length=254, null=True)),
                ('vehicle_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('In Transit', 'In Transit'), ('In Trip', 'In Trip')], default='Online', max_length=100)),
                ('per_day_charge', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('per_day_duration', models.PositiveIntegerField(default=12)),
                ('per_day_duration_type', models.CharField(default='Hr', max_length=200)),
                ('per_day_distance', models.PositiveIntegerField(default=89)),
                ('per_day_distance_type', models.CharField(default='Km', max_length=200)),
                ('driver_name', models.CharField(default='driver Name', max_length=200)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bank Name', max_length=200)),
                ('account', models.CharField(default='Account', max_length=200)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='name', max_length=256)),
                ('driver_desc', models.CharField(default='desc', max_length=256)),
                ('driver_no', phonenumber_field.modelfields.PhoneNumberField(default='+911234567890', max_length=128, region='IN')),
                ('driver_license_no', models.CharField(default='license', max_length=254, unique=True)),
                ('driver_photo_url', models.CharField(max_length=254, null=True)),
                ('license_photo_url', models.CharField(max_length=254, null=True)),
                ('driver_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.CharField(max_length=200)),
                ('quantity_used', models.IntegerField(default=0)),
                ('ph_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=200)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('stock_status', models.CharField(choices=[('Picked up', 'Picked up'), ('Received', 'Received'), ('Qc Done', 'Qc Done'), ('Inventory', 'Inventory')], default='Picked up', max_length=200)),
                ('received_at', models.DateTimeField(null=True)),
                ('picked_at', models.DateTimeField(null=True)),
                ('qc_done_at', models.DateTimeField(null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.driver')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farm')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_note', models.CharField(default='remarks', max_length=200)),
                ('baseProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_base_products', to='product.baseproduct')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_inline', to='warehouse.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockSourceDestinationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0)),
                ('dataName', models.CharField(default='Name', max_length=200)),
                ('dataProfile', models.CharField(choices=[('Farmer', 'Farmer'), ('Vehicle', 'Vehicle'), ('Warehouse', 'Warehouse'), ('Operations', 'Operations'), ('Qc', 'Qc')], default='Farmer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_desc', models.CharField(max_length=256, null=True)),
                ('vehicle_no', models.CharField(default='Vehicle No', max_length=254, unique=True)),
                ('vehicle_identifier', models.CharField(choices=[('Echo', 'Echo'), ('PIAGGIO', 'PIAGGIO'), ('TATA ACE', 'TATA ACE'), ('AUTO', 'AUTO'), ('ASHOK LEYLAND', 'ASHOK LEYLAND'), ('Bolero', 'Bolero'), ('OTHER', 'OTHER')], default='Echo', max_length=254)),
                ('vehicle_identifier_type', models.CharField(default='Echo', max_length=254)),
                ('vendor', models.CharField(default='vendor name', max_length=254)),
                ('vendor_contact_no', phonenumber_field.modelfields.PhoneNumberField(default='+911234567890', max_length=128, region='IN')),
                ('vehicle_photo_url', models.CharField(max_length=254, null=True)),
                ('vendor_photo_url', models.CharField(max_length=254, null=True)),
                ('vehicle_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('In Transit', 'In Transit'), ('In Trip', 'In Trip')], default='Online', max_length=100)),
                ('per_day_charge', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('per_day_duration', models.PositiveIntegerField(default=12)),
                ('per_day_duration_type', models.CharField(default='Hr', max_length=200)),
                ('per_day_distance', models.PositiveIntegerField(default=89)),
                ('per_day_distance_type', models.CharField(default='Km', max_length=200)),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.driver')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('warehouse_type', models.CharField(choices=[('EPC', 'EPC'), ('Distribution', 'Distribution')], default='EPC', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_auth.address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.city')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.cluster')),
                ('clusters', models.ManyToManyField(blank=True, related_name='warehouseClusters', to='base.Cluster')),
            ],
            options={
                'ordering': ('-slug',),
            },
        ),
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastage_type', models.CharField(choices=[('Broken', 'Broken'), ('Chatki', 'Chatki')], max_length=100)),
                ('name', models.CharField(default='name', max_length=256)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('counted_quantity', models.IntegerField(default=0)),
                ('wastage_remark', models.CharField(default='wastage remark', max_length=256)),
                ('stock_inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_inline', to='warehouse.stockinline')),
            ],
        ),
        migrations.CreateModel(
            name='WarehousePersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_status', models.CharField(choices=[('Manager', 'Manager'), ('Regional Manager', 'Regional Manager'), ('Worker', 'Worker')], default='Worker', max_length=100)),
                ('is_test_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_employee', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_person', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('operation_option', models.CharField(choices=[('Egg Pick up', 'Egg Pick up'), ('Delivery', 'Delivery')], max_length=100)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('OnTheWay', 'OnTheWay'), ('Done', 'Done')], default='Assigned', max_length=100)),
                ('desc', models.CharField(max_length=256)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_person_assignment', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_assignment', to='warehouse.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehicle_assignment', to='warehouse.vehicle')),
                ('warehouseEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehousepersonprofile')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='from_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_from', to='warehouse.stocksourcedestinationdata'),
        ),
        migrations.AddField(
            model_name='stock',
            name='operationsPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockOperationsManager', to='operationschain.operationspersonprofile'),
        ),
        migrations.AddField(
            model_name='stock',
            name='productDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stocksproductdivision', to='product.productdivision'),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplyPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockSupplyPerson', to='supplychain.supplypersonprofile'),
        ),
        migrations.AddField(
            model_name='stock',
            name='to_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_to', to='warehouse.stocksourcedestinationdata'),
        ),
        migrations.AddField(
            model_name='stock',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.vehicle'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_Stock', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehousePerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockWarehouseManager', to='warehouse.warehousepersonprofile'),
        ),
        migrations.CreateModel(
            name='QCLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('ph_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('qcEntry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.qcentry')),
            ],
        ),
        migrations.AddField(
            model_name='qcentry',
            name='stock_inline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_qc_inline', to='warehouse.stockinline'),
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('expense_type', models.CharField(default='OTHER', max_length=200)),
                ('city', models.CharField(default='Gurgaon', max_length=200)),
                ('description', models.CharField(default='Paid to', max_length=254)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], max_length=200)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.expensecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenseRequestUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('expense_type', models.CharField(default='OTHER', max_length=200)),
                ('description', models.CharField(default='Paid to', max_length=254)),
                ('city', models.CharField(default='Gurgaon', max_length=200)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('payment_mode', models.CharField(default='PETTY CASH', max_length=200)),
                ('bill_no', models.CharField(default='bill', max_length=200)),
                ('vendor', models.CharField(default='Vendor Name', max_length=200)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenseFinancePerson', to='finance.financeprofile')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.expensecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenseUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='EggProductStockInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=256)),
                ('sku_type', models.CharField(choices=[('Full', 'Full Tray'), ('Single', 'Single'), ('Chatki', 'Chatki')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('stock_inline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_stock_inline', to='warehouse.stockinline')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentDistributionPerson', to='distributionchain.distributionpersonprofile')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentFinancePerson', to='finance.financeprofile')),
                ('salesPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentSalesPerson', to='saleschain.salespersonprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DailyPaymentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('dailyPayment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_payment_lines', to='warehouse.dailypayments')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='BeatInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('desc', models.CharField(default='desc', max_length=256)),
                ('inventory_status', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='Out', max_length=200)),
                ('beat_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributionchain.beatassignment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='beatInventoryAdmin', to='warehouse.warehousepersonprofile')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='Deposit', max_length=100)),
                ('description', models.CharField(default='Paid to', max_length=254)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('deposit_mode', models.CharField(default='PETTY CASH', max_length=200)),
                ('deposit_id', models.CharField(default='ID', max_length=200)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.bankdetails')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depositFinancePerson', to='finance.financeprofile')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('batch_id', 'stock_status')},
        ),
        migrations.CreateModel(
            name='PackedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='packed inventory name', max_length=254)),
                ('desc', models.CharField(default='desc', max_length=256)),
                ('category_type', models.CharField(choices=[('White', 'White'), ('Brown', 'Brown'), ('Nutra', 'Nutra')], default='White', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_status', models.CharField(choices=[('available', 'available'), ('in transit', 'in transit'), ('delivered', 'delivered')], default='available', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryPackedProducts', to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('warehouse', 'name', 'product', 'inventory_status')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inventory name', max_length=254)),
                ('desc', models.CharField(default='desc', max_length=256)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('branded_quantity', models.PositiveIntegerField(default=0)),
                ('unbranded_quantity', models.PositiveIntegerField(default=0)),
                ('chatki_quantity', models.PositiveIntegerField(default=0)),
                ('inventory_status', models.CharField(choices=[('picked up', 'picked up'), ('received', 'received'), ('Qc Done', 'Qc Done'), ('available', 'available'), ('in packing', 'in packing'), ('packed', 'packed'), ('in transit', 'in transit'), ('delivered', 'delivered')], default='available', max_length=200)),
                ('baseProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryBaseProducts', to='product.baseproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('warehouse', 'name', 'baseProduct', 'inventory_status')},
            },
        ),
        migrations.CreateModel(
            name='BeatInventoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('beat_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beat_inventory_line', to='warehouse.beatinventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryBeatProducts', to='product.product')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('product', 'beat_inventory')},
            },
        ),
    ]
