# Generated by Django 3.1.2 on 2021-09-11 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='name', max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\d{10,10}$')])),
                ('packaging_date', models.DateField()),
                ('batch_no', models.CharField(max_length=200)),
                ('issue_type', models.CharField(default='General Query', max_length=256)),
                ('issue', models.CharField(max_length=300)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(help_text='first name', max_length=256)),
                ('last_name', models.CharField(help_text='last name', max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 10 digits allowed.", regex='^\\d{10,10}$')])),
                ('query_type', models.CharField(default='General Query', max_length=256)),
                ('message', models.CharField(max_length=300)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ('feedback_date',),
            },
        ),
        migrations.CreateModel(
            name='FarmerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('query_type', models.CharField(default='Help Query', max_length=256)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to)),
                ('is_resolved', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farmer_feedbacks', to='farmer.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
