# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=200)),
                ('client_topic', models.CharField(help_text='863958048443779', max_length=255)),
                ('temperature', models.DecimalField(decimal_places=6, default=0, help_text='40.92', max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=6, default=0, help_text='95726.73', max_digits=15)),
                ('ammonia_r', models.DecimalField(decimal_places=6, default=0, help_text='23', max_digits=15)),
                ('ammonia_ppm', models.DecimalField(decimal_places=6, default=0, help_text='9.66429', max_digits=15)),
                ('Sq', models.DecimalField(decimal_places=6, default=0, help_text='25', max_digits=15)),
                ('BATV', models.DecimalField(decimal_places=6, default=0, help_text='3.29', max_digits=15)),
                ('BATQ', models.DecimalField(decimal_places=6, default=0, help_text='247', max_digits=15)),
            ],
        ),
    ]
