# Generated by Django 3.1.2 on 2021-09-19 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcleaning',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='eggcleaning',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eggqualitycheck',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='eggsin',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_eggsin_set', to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='eggsin',
            name='procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procurement_eggsin_set', to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='eggsin',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='quality_param1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='quality_param2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='quality_param3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurementperwarehouse',
            name='procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.procurement'),
        ),
        migrations.AlterField(
            model_name='procurementperwarehouse',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='returnedpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.package'),
        ),
        migrations.AlterField(
            model_name='returnedpackage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
