# Generated by Django 3.1.2 on 2021-09-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20210919_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcurementMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.CharField(blank=True, default='test', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='procurement',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
