# Generated by Django 3.1.2 on 2021-09-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_auto_20210922_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggsin',
            name='egg_count',
        ),
        migrations.RemoveField(
            model_name='eggsin',
            name='egg_type',
        ),
        migrations.RemoveField(
            model_name='eggsin',
            name='procurement',
        ),
        migrations.AddField(
            model_name='eggsin',
            name='egg_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eggsin',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_eggsin_set', to='procurement.procurement'),
        ),
    ]
