# Generated by Django 3.1.2 on 2021-09-24 05:36

from django.db import migrations, models
import django.utils.timezone
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_auto_20210922_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=uuid_upload_path.storage.upload_to)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='batchprocurementmapping',
            name='procurement_bill_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='batch_egg_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
