# Generated by Django 3.1.2 on 2021-09-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import procurement.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0002_auto_20210911_1424'),
        ('warehouse', '0001_initial'),
        ('procurement', '0007_auto_20210924_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, default=procurement.models.batch_generator, max_length=15, unique=True)),
                ('egg_type', models.CharField(choices=[('White', 'White'), ('Brown', 'Brown')], max_length=30)),
                ('batch_egg_image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('egg_count', models.IntegerField(default=0)),
                ('quality_param1', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_param2', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_param3', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchPerWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.batchmodel')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='BatchProcurementMapping',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='batch_egg_image_url',
            new_name='procurement_bill_url',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='egg_count',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='egg_type',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='procurement_id',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='quality_param1',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='quality_param2',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='quality_param3',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='eggsin',
            name='egg_chatki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggsin',
            name='egg_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procurement',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmer.farmer'),
        ),
        migrations.DeleteModel(
            name='ProcurementPerWarehouse',
        ),
        migrations.AddField(
            model_name='batchmodel',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.procurement'),
        ),
        migrations.AddField(
            model_name='batchmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eggcleaning',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.batchmodel'),
        ),
        migrations.AlterField(
            model_name='eggqualitycheck',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.batchmodel'),
        ),
        migrations.AlterField(
            model_name='eggsin',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_eggsin_set', to='procurement.batchmodel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.batchmodel'),
        ),
    ]
