# Generated by Django 3.1.2 on 2021-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_auto_20210924_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmodel',
            name='egg_ph',
            field=models.FloatField(default=0),
        ),
    ]
