# Generated by Django 3.1.2 on 2021-09-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_auto_20210925_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggcleaning',
            old_name='chatki',
            new_name='egg_chatki',
        ),
        migrations.RenameField(
            model_name='eggcleaning',
            old_name='losses',
            new_name='egg_loss',
        ),
    ]
