# Generated by Django 3.1.2 on 2021-09-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_eggcleaning_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggqualitycheck',
            old_name='chatki',
            new_name='egg_chatki',
        ),
        migrations.RenameField(
            model_name='eggqualitycheck',
            old_name='intact',
            new_name='egg_count',
        ),
        migrations.RenameField(
            model_name='eggqualitycheck',
            old_name='losses',
            new_name='egg_loss',
        ),
        migrations.RemoveField(
            model_name='eggqualitycheck',
            name='egg_type',
        ),
        migrations.AlterField(
            model_name='eggqualitycheck',
            name='batch_id',
            field=models.OneToOneField(db_column='batch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.batchmodel'),
        ),
    ]
