# Generated by Django 3.1.2 on 2021-09-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_auto_20210926_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='chatki',
            new_name='egg_chatki',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='intact',
            new_name='egg_count',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='losses',
            new_name='egg_loss',
        ),
    ]
