# Generated by Django 3.1.2 on 2021-09-30 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_auto_20210928_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcleaning',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='eggcleaning',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
