# Generated by Django 3.1.2 on 2021-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_package_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='sku',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
