# Generated by Django 3.1.2 on 2021-10-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('procurement', '0021_auto_20211005_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='sku',
            new_name='sku_count',
        ),
        migrations.RemoveField(
            model_name='package',
            name='egg_count',
        ),
        migrations.RemoveField(
            model_name='package',
            name='end_time',
        ),
        migrations.AddField(
            model_name='package',
            name='package_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
    ]
