# Generated by Django 3.1.2 on 2021-10-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_remove_package_egg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchmodel',
            old_name='egg_count',
            new_name='actual_egg_count',
        ),
        migrations.RenameField(
            model_name='batchmodel',
            old_name='egg_price',
            new_name='expected_egg_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sku_count',
        ),
        migrations.AddField(
            model_name='batchmodel',
            name='expected_egg_count',
            field=models.IntegerField(default=0),
        ),
    ]
