# Generated by Django 3.1.2 on 2021-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_auto_20211016_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmodel',
            name='actual_egg_price',
            field=models.FloatField(default=0),
        ),
    ]
