# Generated by Django 3.1.2 on 2021-09-11 08:54

import base.util.json_serializer
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '__first__'),
        ('distributionchain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNoteTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_transaction', models.PositiveIntegerField(default=0)),
                ('debit_note_date', models.DateTimeField(blank=True, help_text='date of debit note', null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=200, null=True)),
                ('orderId', models.CharField(max_length=254, unique=True)),
                ('order_type', models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Retailer', 'Retailer'), ('Customer', 'Customer')], default='Retailer', max_length=254)),
                ('order_brand_type', models.CharField(choices=[('branded', 'branded'), ('unbranded', 'unbranded')], default='branded', max_length=254)),
                ('pending_transaction', models.PositiveIntegerField(default=0)),
                ('refund_transaction', models.PositiveIntegerField(default=0)),
                ('pay_by_wallet', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('created', 'created'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('packing', 'packing'), ('packed', 'packed'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('closed', 'closed'), ('cancelled', 'cancelled'), ('open_purchase_order', 'open_po'), ('close_purchase_order', 'closed_po')], default='created', max_length=32)),
                ('secondary_status', models.CharField(choices=[('created', 'created'), ('delivered', 'delivered'), ('revised', 'revised'), ('picked', 'picked'), ('refund', 'refund'), ('delayed', 'delayed'), ('replacement', 'replacement'), ('return', 'return'), ('partial_refund', 'partial_refund'), ('partial_replace', 'partial_replace'), ('partial_return', 'partial_return'), ('partial_refund_replace', 'partial_refund_replace'), ('partial_return_replace', 'partial_return_replace'), ('partial_return_refund', 'partial_return_refund'), ('return_picked', 'return_picked'), ('cancel_requested', 'cancel_requested'), ('cancel_approved', 'cancel_approved')], default='created', max_length=32)),
                ('date', models.DateTimeField(blank=True, help_text='date of creation', null=True)),
                ('generation_date', models.DateTimeField(auto_now_add=True, help_text='date of generation')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='date of delivery', null=True)),
                ('dispatch_date', models.DateTimeField(blank=True, help_text='date of dispatch', null=True)),
                ('return_picked_date', models.DateTimeField(blank=True, help_text='date of return picked', null=True)),
                ('retailer_note', models.CharField(blank=True, default='retailer note', max_length=254, null=True)),
                ('deviated_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('discount_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_price_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order_payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('order_final_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_trial', models.BooleanField(default=False)),
                ('is_geb', models.BooleanField(default=False)),
                ('is_geb_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('manage_orders', 'Manage orders.'),),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('draft_created', 'draft_created'), ('draft_added_products', 'draft_added_products'), ('draft_removed_products', 'draft_removed_products'), ('placed', 'placed'), ('delivery_date_revised', 'delivery_date_revised'), ('placed_from_draft', 'placed_from_draft'), ('oversold_items', 'oversold_items'), ('canceled', 'canceled'), ('order_marked_as_paid', 'order_marked_as_paid'), ('order_fully_paid', 'order_fully_paid'), ('updated_address', 'updated_address'), ('email_sent', 'email_sent'), ('payment_authorized', 'payment_authorized'), ('payment_captured', 'payment_captured'), ('external_service_notification', 'external_service_notification'), ('payment_refunded', 'payment_refunded'), ('payment_voided', 'payment_voided'), ('payment_failed', 'payment_failed'), ('invoice_requested', 'invoice_requested'), ('invoice_generated', 'invoice_generated'), ('invoice_updated', 'invoice_updated'), ('invoice_sent', 'invoice_sent'), ('fulfillment_canceled', 'fulfillment_canceled'), ('fulfillment_restocked_items', 'fulfillment_restocked_items'), ('fulfillment_fulfilled_items', 'fulfillment_fulfilled_items'), ('tracking_updated', 'tracking_updated'), ('note_added', 'note_added'), ('other', 'other')], default='placed', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=base.util.json_serializer.CustomJsonEncoder)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_type', models.CharField(choices=[('Normal', 'Normal'), ('Chatki', 'Chatki'), ('Hairline', 'Hairline'), ('Replaced', 'Replaced'), ('Melted', 'Melted')], default='Normal', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('deviated_quantity', models.IntegerField(default=0)),
                ('promo_quantity', models.IntegerField(default=0)),
                ('deviated_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('single_sku_mrp', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('single_sku_rate', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OrderPendingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_transaction', models.PositiveIntegerField(default=0)),
                ('pending_collection_date', models.DateTimeField(blank=True, help_text='date of return picked', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_id', models.CharField(max_length=254)),
                ('desc', models.CharField(default='desc', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('created', 'created'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('packing', 'packing'), ('packed', 'packed'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('closed', 'closed'), ('cancelled', 'cancelled'), ('open_purchase_order', 'open_po'), ('close_purchase_order', 'closed_po')], default='packing', max_length=32)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='EcommerceOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('desc', models.CharField(default='desc', max_length=200)),
                ('promo_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_promo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.order')),
                ('purchase_id', models.CharField(blank=True, max_length=254, null=True)),
                ('desc', models.CharField(default='desc', max_length=200)),
                ('po_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=32)),
            ],
            options={
                'ordering': ('-pk',),
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ReturnOrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_transaction', models.PositiveIntegerField(default=0)),
                ('return_picked_date', models.DateTimeField(blank=True, help_text='date of return picked', null=True)),
                ('deviated_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('beat_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributionchain.beatassignment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_return_transaction', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReturnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_transaction', models.IntegerField(default=0)),
                ('cancelled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_type', models.CharField(choices=[('Replacement', 'Replacement'), ('Refund', 'Refund'), ('Return', 'Return'), ('Cancelled', 'Cancelled'), ('Promo', 'Promo')], default='Replacement', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('beat_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributionchain.beatassignment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancelledDistributor', to='distributionchain.distributionpersonprofile')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnDistributor', to='distributionchain.distributionpersonprofile')),
                ('financePerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnFinance', to='finance.financeprofile')),
                ('orderLine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lines', to='order.orderline')),
            ],
        ),
    ]
