# Generated by Django 3.1.2 on 2021-09-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20210911_1424'),
        ('ecommerce', '0002_auto_20210911_1424'),
        ('distributionchain', '__first__'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.vehicleassignment'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_orders', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='debitnotetransaction',
            name='beat_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='distributionchain.beatassignment'),
        ),
        migrations.AddField(
            model_name='debitnotetransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_transaction', to='order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('name', 'retailer', 'date', 'delivery_date', 'order_price_amount')},
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='SubscriptionDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecomm_subscrption_dates', to='ecommerce.subscriptiondate'),
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='ecommerce_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.ecommerceslot'),
        ),
    ]
